### ISSUE TITLE
FeatureRequest: Allow optional PATCH (additional to PUT)

### ISSUE THREAD

**Issue by art-cg** [mtarld/api-platform-ms-bundle#53]
Hi. 
Is there a reason why this bundle is useing PUT instead of PATCH for Updates?
Are there any disadvatages of PATCH?

We use actual only PATCH in our APIs. We habe now to decide if we replace it with PUT, 
or create a PR that allows PUT and PATCH for this bundle.
=> Allow optional PATCH (additional to PUT)

Any advise on this topic?

Not tested, just to give some context.

src/HttpRepository/AbstractMicroserviceHttpRepository.php
`public function update(ApiResourceDtoInterface $resource, array $additionalQueryParams = []): ApiResourceDtoInterface
    {
       ...

        try {
            #$response = $this->request('PATCH', $this->buildUri($iri, $additionalQueryParams), $resource, 'application/merge-patch+json', 'json');
            $response = $this->request('PUT', $this->buildUri($iri, $additionalQueryParams), $resource, null, 'json');`

Greetz

**Comment by mtarld** [comment]
Hi @art-cg!

Yes indeed, both `PUT` and `PATCH` methods must be supported.
Actually, I created this bundle because of a project, and in that project, they used the `PUT` method to update resources.
But you're right `PATCH` is legitimate, and moreover, I think that it must be the default one.

I think that we can introduce a container configuration. Something like a switch to specify if we wanna use `PATCH` or `PUT` (with `PUT` to default in `0.x` and with `PATCH` to default in `1.x` to handle BC)
We'll also need to know if it's generic or if it's specific to each microservice.

Are you up for a PR? :slightly_smiling_face:

**Comment by ismail1432** [comment]
Hey guys 👋

Instead of dealing with container configuration what about introduce a new method `patch` method and a new method `put` inside the repository.
We have to depreciate the current `update` method to remove it in favor of `put` in the next major version.

**Comment by mtarld** [comment]
Yep, that's a good idea! Much simpler to implement.
On the other hand, I don't wanna leak the verb into the method's name.

Maybe we can find appropriate names though? Something like:
- `update` -> `PUT` (no BC break)
- `partialUpdate` -> `PATCH`

Any other ideas are welcome!

**Comment by art-cg** [comment]
Thanks for the fast response.
Please let me know how i should implement it. The main goal should be no BC break.

**Comment by ismail1432** [comment]
partialUpdate is a good idea

**Comment by mtarld** [comment]
Nice! So let's do that!

@art-cg, the way to do it quite straightforward:
- add a `partialUpdate` method into the `AbstractMicroserviceHttpRepository`
- update the documentation (`src/Resources/doc/tools/http-repository.md`)
- update tests accordingly (`tests/HttpRepository/HttpRepositoryTest.php`)

Sounds good to you?

**Comment by art-cg** [comment]
Great. I will work on a PR

**Comment by mtarld** [comment]
Close it as #56 is merged
